spring:
  application:
    name: grocery-bot
bot:
  path: ""
  username: GroceryListHelperBot
logging:
  level:
    "org.saphka.telegram.grocery.bot.service.TelegramUpdateProcessor": INFO
    "org.springframework.data.repository.config.RepositoryConfigurationDelegate": WARN
    "org.springframework.context.support.PostProcessorRegistrationDelegate.BeanPostProcessorChecker": WARN